namespace BetterIW4ToDiscord.Configuration;

public class ConfigurationRoot
{
    public WebHooks WebHooks { get; set; } = new();

    public Dictionary<string, Resources.Parser> ParserMap { get; set; } = new()
    {
        // @formatter:off
        ["CoD4x Parser"] = new Resources.Parser("CoD4x","http://orig05.deviantart.net/8749/f/2008/055/0/c/call_of_duty_4__dock_icon_by_watts240.png", 6723840),
        ["H1-Mod Parser"] = new Resources.Parser("H1-Mod","https://i.ibb.co/zS4pc0B/166013016241761317.png", 6723844),
        ["IW4x Parser"] = new Resources.Parser("IW4x","https://i.gyazo.com/758b6933287392106bfdddc24b09d502.png", 11331072),
        ["Tekno MW3 Parser"] = new Resources.Parser("TeknoMW3","https://orig00.deviantart.net/9af1/f/2011/310/2/1/modern_warfare_3_logo_by_wifsimster-d4f9ozd.png", 39219),
        ["Plutonium IW5 Parser"] = new Resources.Parser("PlutoIW5","https://orig00.deviantart.net/9af1/f/2011/310/2/1/modern_warfare_3_logo_by_wifsimster-d4f9ozd.png", 39219),
        ["IW6x Parser"] = new Resources.Parser("IW6x","https://i.gyazo.com/82b84341e141f6420db6c6ef1d9037bb.png", 39321),
        ["Plutonium T4 MP Parser"] = new Resources.Parser("PlutoT4","https://i.gyazo.com/1e1987d84038aae38610cab9c999868d.png", 7829308),
        ["Plutonium T4 CO-OP/Zombies Parser"] = new Resources.Parser("PlutoT4 Singleplayer","https://i.gyazo.com/1e1987d84038aae38610cab9c999868d.png", 7829308),
        ["RektT5m Parser"] = new Resources.Parser("RektT5M","https://i.gyazo.com/a8a22764fafd4cc178329717b9bb35dd.png", 6064778),
        ["Plutonium T5 Parser (2025)"] = new Resources.Parser("PlutoT5","https://i.gyazo.com/a8a22764fafd4cc178329717b9bb35dd.png", 6064778),
        ["Plutonium T6 Parser (2024)"] = new Resources.Parser("PlutoT6","https://i.gyazo.com/5a445c5c733c698b32732550ec797e91.png", 15108608),
        ["Black Ops 3 Parser"] = new Resources.Parser("Call of Duty: Black Ops III","https://i.gyazo.com/5691ca84d47e219cdec76901ff142159.png", 16737792),
        ["BOIII Parser"] = new Resources.Parser("BOIII","https://i.imgur.com/nIi5QFP.jpg", 16737792),
        ["S1x Parser"] = new Resources.Parser("SHG1","https://i.gyazo.com/d524bf93e1fc38fa46f8fe1ed5162493.png", 13421568),
        ["CS:GO Parser"] = new Resources.Parser("CSGO","https://www.freeiconspng.com/uploads/csgo-icon-4.png", 1911881),
        ["CS:GO (SourceMod) Parser"] = new Resources.Parser("CSGO (SourceMod)","https://www.freeiconspng.com/uploads/csgo-icon-4.png", 1911881),
        ["H2M-Mod Parser"] = new Resources.Parser("H2MMOD","https://i.imgur.com/IkPHQi7.png", 6723844),
        ["IW7-Mod Parser"] = new Resources.Parser("IW7MOD","https://imgur.com/a/GEY4A0q", 6723844),
        ["L4D2 (SourceMod) Parser"] = new Resources.Parser("L4D2","https://icons.iconarchive.com/icons/3xhumed/mega-games-pack-31/256/Left4Dead-2-2-icon.png", 6723844)
        // @formatter:on
    };

    public Dictionary<string, List<Resources.Map>> GameImageMap { get; set; } = new()
    {
        // @formatter:off
        ["IW3"] =
        [
            new Resources.Map("mp_convoy", "https://static.wikia.nocookie.net/callofduty/images/3/3c/Bare_Load_Screen_Ambush_CoD4.jpg/revision/latest?cb=20100723075603"),
            new Resources.Map("mp_backlot", "https://static.wikia.nocookie.net/callofduty/images/0/0f/Backlot_loadscreen_CoD4.jpg/revision/latest?cb=20100723075613"),
            new Resources.Map("mp_bloc", "https://static.wikia.nocookie.net/callofduty/images/9/9d/Bare_Load_Screen_Bloc_CoD4.jpg/revision/latest?cb=20100723075638"),
            new Resources.Map("mp_bog", "https://static.wikia.nocookie.net/callofduty/images/2/29/Bog_Map_Image_CoD4.jpg/revision/latest?cb=20100723075648"),
            new Resources.Map("mp_countdown", "https://static.wikia.nocookie.net/callofduty/images/e/e9/Bare_Load_Screen_Countdown_CoD4.jpg/revision/latest?cb=20100723075829"),
            new Resources.Map("mp_crash", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Crash-CoD4.jpg"),
            new Resources.Map("mp_crossfire", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-crossfire.jpg"),
            new Resources.Map("mp_citystreets", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-district.jpg"),
            new Resources.Map("mp_farm", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Downpour-CoD4.jpg"),
            new Resources.Map("mp_overgrown", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Overgrown-CoD4.jpg"),
            new Resources.Map("mp_pipeline", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-pipeline.jpg"),
            new Resources.Map("mp_shipment", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Shipment-Load.jpg"),
            new Resources.Map("mp_showdown", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Showdown-MWR.jpg"),
            new Resources.Map("mp_strike", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Cod4-map-strike.jpg"),
            new Resources.Map("mp_vacant", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-vacant.jpg"),
            new Resources.Map("mp_cargoship", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Cod4-map-wetwork.jpg"),
            new Resources.Map("mp_crash_snow", "https://static.wikia.nocookie.net/callofduty/images/f/f7/Bare_Load_Screen_Winter_Crash_CoD4.jpg/revision/latest?cb=20100723080720"),
            new Resources.Map("mp_broadcast", "https://static.wikia.nocookie.net/callofduty/images/e/ec/Broadcast_loading_screen_CoD4.jpg/revision/latest?cb=20100723080927"),
            new Resources.Map("mp_creek", "https://static.wikia.nocookie.net/callofduty/images/e/e1/CreekCOD4.jpg/revision/latest?cb=20100723075941"),
            new Resources.Map("mp_carentan", "https://static.wikia.nocookie.net/callofduty/images/0/0c/ChinatownCOD4.jpg/revision/latest?cb=20110727174233"),
            new Resources.Map("mp_killhouse", "https://static.wikia.nocookie.net/callofduty/images/4/48/Cod4-killhouse.jpg/revision/latest?cb=20100723081127"),
        ],
        ["IW4"] =
        [
            new Resources.Map("mp_rust", "https://static.wikia.nocookie.net/callofduty/images/3/33/Rust.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("mp_terminal", "https://static.wikia.nocookie.net/callofduty/images/1/14/Bare_Load_Screen_Terminal_MW2.jpg/revision/latest?cb=20100720174519"),
            new Resources.Map("mp_crash", "https://static.wikia.nocookie.net/callofduty/images/9/9f/Bare_Load_Screen_Crash_MW2.jpg/revision/latest?cb=20100613115705"),
            new Resources.Map("mp_afghan", "https://static.wikia.nocookie.net/callofduty/images/8/83/Afghan_loading_screen_MW2.png/revision/latest?cb=20130310131229"),
            new Resources.Map("mp_derail", "https://static.wikia.nocookie.net/callofduty/images/2/20/Derail.jpg/revision/latest?cb=20100720174408"),
            new Resources.Map("mp_estate", "https://static.wikia.nocookie.net/callofduty/images/9/91/Estate.jpg/revision/latest?cb=20100720174409"),
            new Resources.Map("mp_favela", "https://static.wikia.nocookie.net/callofduty/images/2/29/Favela_Map_MW2.jpg/revision/latest?cb=20100720174410"),
            new Resources.Map("mp_highrise", "https://static.wikia.nocookie.net/callofduty/images/4/49/Highrise-promo.jpg/revision/latest?cb=20100720174411"),
            new Resources.Map("mp_invasion", "https://static.wikia.nocookie.net/callofduty/images/9/95/Invasion_MW2.jpg/revision/latest?cb=20100720174410"),
            new Resources.Map("mp_checkpoint", "https://static.wikia.nocookie.net/callofduty/images/9/9f/Karachi-prev.jpg/revision/latest?cb=20100720174412"),
            new Resources.Map("mp_quarry", "https://static.wikia.nocookie.net/callofduty/images/8/8a/Loadscreen_mp_quarry.jpg/revision/latest?cb=20091207173135"),
            new Resources.Map("mp_rundown", "https://static.wikia.nocookie.net/callofduty/images/3/3a/Rundown-prev.jpg/revision/latest?cb=20100720174412"),
            new Resources.Map("mp_boneyard", "https://static.wikia.nocookie.net/callofduty/images/e/ef/Scrapyard.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("mp_nightshift", "https://static.wikia.nocookie.net/callofduty/images/d/d2/Skidrow.jpg/revision/latest?cb=20100720174516"),
            new Resources.Map("mp_subbase", "https://static.wikia.nocookie.net/callofduty/images/1/1e/Sub_Base.jpg/revision/latest?cb=20100720174517"),
            new Resources.Map("mp_underpass", "https://static.wikia.nocookie.net/callofduty/images/b/b5/Underpass.jpg/revision/latest?cb=20100720174519"),
            new Resources.Map("mp_brecourt", "https://static.wikia.nocookie.net/callofduty/images/c/cc/Wasteland.jpg/revision/latest?cb=20100720174520"),
            new Resources.Map("mp_overgrown", "https://static.wikia.nocookie.net/callofduty/images/7/7d/Bare_Load_Screen_Overgrown_CoD4.jpg/revision/latest?cb=20110727174104"),
            new Resources.Map("mp_strike", "https://static.wikia.nocookie.net/callofduty/images/b/b0/Loadscreen_mp_strike.jpg/revision/latest?cb=20100712195725"),
            new Resources.Map("mp_vacant", "https://static.wikia.nocookie.net/callofduty/images/6/67/Loadscreen_mp_vacant.jpg/revision/latest?cb=20100712195617"),
            new Resources.Map("mp_abandon", "https://static.wikia.nocookie.net/callofduty/images/c/c3/Carnival_loadscreen.jpg/revision/latest?cb=20100712195429"),
            new Resources.Map("mp_trailerpark", "https://static.wikia.nocookie.net/callofduty/images/c/cf/Trailer_Park.jpg/revision/latest?cb=20100712195448"),
            new Resources.Map("mp_fuel2", "https://static.wikia.nocookie.net/callofduty/images/d/de/Fuel_loadscreen.jpg/revision/latest?cb=20100712195521"),
            new Resources.Map("mp_storm", "https://static.wikia.nocookie.net/callofduty/images/6/60/MW2_Storm.jpg/revision/latest?cb=20100613115722"),
            new Resources.Map("mp_complex", "https://static.wikia.nocookie.net/callofduty/images/0/0e/MW2_Bailout.jpg/revision/latest?cb=20100613115812"),
            new Resources.Map("mp_compact", "https://static.wikia.nocookie.net/callofduty/images/d/d7/MW2_Salvage.jpg/revision/latest?cb=20100613115824"),
            new Resources.Map("mp_nuked", "https://i.ytimg.com/vi/ysr0CyyJx8E/maxresdefault.jpg"),
            new Resources.Map("iw4_credits", "https://i.ytimg.com/vi/VniF3DnE5uk/maxresdefault.jpg"),
            new Resources.Map("mp_killhouse", "https://static.wikia.nocookie.net/callofduty/images/4/48/Cod4-killhouse.jpg/revision/latest?cb=20100723081127"),
            new Resources.Map("mp_bog_sh", "https://static.wikia.nocookie.net/callofduty/images/2/29/Bog_Map_Image_CoD4.jpg/revision/latest?cb=20100723075648"),
            new Resources.Map("mp_cargoship_sh", "https://static.wikia.nocookie.net/callofduty/images/d/d4/Cargo_loadscreen_BOII.png/revision/latest?cb=20130120072815"),
            new Resources.Map("mp_cargoship", "https://static.wikia.nocookie.net/callofduty/images/d/d4/Cargo_loadscreen_BOII.png/revision/latest?cb=20130120072815"),
            new Resources.Map("mp_shipment", "https://static.wikia.nocookie.net/callofduty/images/9/9b/Shipment_Load.jpg/revision/latest?cb=20100723080524"),
            new Resources.Map("mp_shipment_long", "https://static.wikia.nocookie.net/callofduty/images/9/9b/Shipment_Load.jpg/revision/latest?cb=20100723080524"),
            new Resources.Map("mp_rust_long", "https://static.wikia.nocookie.net/callofduty/images/3/33/Rust.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("mp_firingrange", "https://static.wikia.nocookie.net/callofduty/images/8/82/Bare_Load_Screen_Firing_Range_BO.jpg/revision/latest?cb=20110303121918"),
            new Resources.Map("mp_storm_spring", "https://static.wikia.nocookie.net/callofduty/images/6/60/MW2_Storm.jpg/revision/latest?cb=20100613115722"),
            new Resources.Map("mp_fav_tropical", "https://static.wikia.nocookie.net/callofduty/images/2/29/Favela_Map_MW2.jpg/revision/latest?cb=20100720174410"),
            new Resources.Map("mp_estate_tropical", "https://static.wikia.nocookie.net/callofduty/images/9/91/Estate.jpg/revision/latest?cb=20100720174409"),
            new Resources.Map("mp_crash_tropical", "https://static.wikia.nocookie.net/callofduty/images/9/9f/Bare_Load_Screen_Crash_MW2.jpg/revision/latest?cb=20100613115705"),
            new Resources.Map("mp_bloc_sh", "https://static.wikia.nocookie.net/callofduty/images/9/9d/Bare_Load_Screen_Bloc_CoD4.jpg/revision/latest?cb=20100723075638"),
            new Resources.Map("mp_cross_fire", "https://static.wikia.nocookie.net/callofduty/images/5/53/Cod4_map_crossfire.jpg/revision/latest?cb=20100723075954"),
            new Resources.Map("mp_bloc", "https://static.wikia.nocookie.net/callofduty/images/9/9d/Bare_Load_Screen_Bloc_CoD4.jpg/revision/latest?cb=20100723075638"),
            new Resources.Map("oilrig", "https://static.wikia.nocookie.net/callofduty/images/3/30/Mg_oilrig.jpg/revision/latest480?cb=20120716172859"),
            new Resources.Map("co_hunted", "https://static.wikia.nocookie.net/callofduty/images/f/f4/Bare_Load_Screen_Village_MW3.png/revision/latest?cb=20120320235505"),
        ],
        ["IW5"] =
        [
            new Resources.Map("mp_seatown", "https://static.wikia.nocookie.net/callofduty/images/a/a7/Bare_Load_Screen_Seatown_MW3.png/revision/latest?cb=20120320235504"),
            new Resources.Map("mp_alpha", "https://static.wikia.nocookie.net/callofduty/images/a/a6/Lockdown_loading_screen_MW3.PNG/revision/latest?cb=20130728192041"),
            new Resources.Map("mp_bravo", "https://static.wikia.nocookie.net/callofduty/images/2/20/Bare_Load_Screen_Mission_MW3.png/revision/latest?cb=20120320235416"),
            new Resources.Map("mp_carbon", "https://static.wikia.nocookie.net/callofduty/images/c/c8/Bare_Load_Screen_Carbon_MW3.png/revision/latest?cb=20120320235417"),
            new Resources.Map("mp_dome", "https://static.wikia.nocookie.net/callofduty/images/f/f1/Bare_Load_Screen_Dome_MW3.png/revision/latest?cb=20120320235417"),
            new Resources.Map("mp_plaza2", "https://static.wikia.nocookie.net/callofduty/images/6/65/Bare_Loading_Screen_Arkaden_MW3.png/revision/latest?cb=20120519230749"),
            new Resources.Map("mp_exchange", "https://static.wikia.nocookie.net/callofduty/images/5/52/Bare_Load_Screen_Downturn_MW3.png/revision/latest?cb=20120320235418"),
            new Resources.Map("mp_bootleg", "https://static.wikia.nocookie.net/callofduty/images/5/52/Bare_Load_Screen_Downturn_MW3.png/revision/latest?cb=20120320235418"),
            new Resources.Map("mp_hardhat", "https://static.wikia.nocookie.net/callofduty/images/5/5a/Bare_Load_Screen_Hardhat_MW3.png/revision/latest?cb=20120519225919"),
            new Resources.Map("mp_interchange", "https://static.wikia.nocookie.net/callofduty/images/4/4b/Bare_Load_Screen_Interchange_MW3.png/revision/latest?cb=20120320235418"),
            new Resources.Map("mp_lambeth", "https://static.wikia.nocookie.net/callofduty/images/d/d8/Bare_Loading_Screen_Fallen_MW3.png/revision/latest?cb=20120320235419"),
            new Resources.Map("mp_radar", "https://static.wikia.nocookie.net/callofduty/images/3/3c/Bare_Load_Screen_Outpost_MW3.png/revision/latest?cb=20120320235504"),
            new Resources.Map("mp_mogadishu", "https://static.wikia.nocookie.net/callofduty/images/3/39/Bare_Load_Screen_Bakaara_MW3.png/revision/latest?cb=20120320235502"),
            new Resources.Map("mp_paris", "https://static.wikia.nocookie.net/callofduty/images/f/fe/Bare_Load_Screen_Resistance_MW3.png/revision/latest?cb=20120320235503"),
            new Resources.Map("mp_underground", "https://static.wikia.nocookie.net/callofduty/images/0/09/Bare_Load_Screen_Underground_MW3.png/revision/latest?cb=20120320235504"),
            new Resources.Map("mp_village", "https://static.wikia.nocookie.net/callofduty/images/f/f4/Bare_Load_Screen_Village_MW3.png/revision/latest?cb=20120320235505"),
            new Resources.Map("mp_aground_ss", "https://static.wikia.nocookie.net/callofduty/images/3/31/Sideview_Aground_MW3.jpg/revision/latest?cb=20120512095024"),
            new Resources.Map("mp_boardwalk", "https://static.wikia.nocookie.net/callofduty/images/2/2c/Boardwalk_loadscreen_MW3.png/revision/latest?cb=20140411094526"),
            new Resources.Map("mp_burn_ss", "https://static.wikia.nocookie.net/callofduty/images/d/d0/U-Turn_loadscreen_MW3.png/revision/latest?cb=20140411095015"),
            new Resources.Map("mp_cement", "https://static.wikia.nocookie.net/callofduty/images/0/0f/Foundation_loadscreen_MW3.png/revision/latest?cb=20140411095546"),
            new Resources.Map("mp_courtyard_ss", "https://static.wikia.nocookie.net/callofduty/images/4/46/Main_Statue_Erosion_MW3.jpg/revision/latest?cb=20120512094647"),
            new Resources.Map("mp_crosswalk_ss", "https://static.wikia.nocookie.net/callofduty/images/d/dd/Intersection_loadscreen_MW3.png/revision/latest?cb=20140411100832"),
            new Resources.Map("mp_hillside_ss", "https://static.wikia.nocookie.net/callofduty/images/1/1f/Bare_Load_Screen_Getaway_MW3.jpg/revision/latest?cb=20120512095322"),
            new Resources.Map("mp_italy", "https://static.wikia.nocookie.net/callofduty/images/3/38/Bare_Load_Screen_Piazza_MW3.jpg/revision/latest?cb=20120110185200"),
            new Resources.Map("mp_meteora", "https://static.wikia.nocookie.net/callofduty/images/4/4b/Bare_Load_Screen_Sanctuary_MW3.jpg/revision/latest?cb=20120410173611"),
            new Resources.Map("mp_moab", "https://static.wikia.nocookie.net/callofduty/images/3/30/Bridge_Gulch_MW3.jpg/revision/latest?cb=20120802172028"),
            new Resources.Map("mp_morningwood", "https://static.wikia.nocookie.net/callofduty/images/d/d1/Bare_Load_Screen_Black_Box_MW3.jpg/revision/latest?cb=20120309203305"),
            new Resources.Map("mp_nola", "https://static.wikia.nocookie.net/callofduty/images/a/aa/Missiles_Parish_MW3.jpg/revision/latest?cb=20120802172330"),
            new Resources.Map("mp_overwatch", "https://static.wikia.nocookie.net/callofduty/images/3/35/Bare_Load_Screen_Overwatch_MW3.jpg/revision/latest?cb=20120207181435"),
            new Resources.Map("mp_park", "https://static.wikia.nocookie.net/callofduty/images/e/e8/Bare_Load_Screen_Liberation_MW3.png/revision/latest?cb=20120120153252"),
            new Resources.Map("mp_qadeem", "https://static.wikia.nocookie.net/callofduty/images/c/c1/Bare_Load_Screen_Oasis_MW3.jpg/revision/latest?cb=20120512100009"),
            new Resources.Map("mp_restrepo_ss", "https://static.wikia.nocookie.net/callofduty/images/2/28/Bare_Load_Screen_Lookout_MW3.jpg/revision/latest?cb=20120512095607"),
            new Resources.Map("mp_roughneck", "https://static.wikia.nocookie.net/callofduty/images/2/2d/Crane_Off_Shore_MW3.jpg/revision/latest?cb=20120712172115"),
            new Resources.Map("mp_shipbreaker", "https://static.wikia.nocookie.net/callofduty/images/4/4f/Bare_ELITE_Calendar_Decommission_MW3.jpg/revision/latest?cb=20120802171643"),
            new Resources.Map("mp_six_ss", "https://static.wikia.nocookie.net/callofduty/images/2/2a/Bare_ELITE_Calendar_Vortex_MW3.jpg/revision/latest?cb=20120624135437"),
            new Resources.Map("mp_terminal_cls", "https://static.wikia.nocookie.net/callofduty/images/6/68/Terminal_Loading_Screen_MW3.png/revision/latest?cb=20120826091508"),
            new Resources.Map("mp_rust", "https://static.wikia.nocookie.net/callofduty/images/3/33/Rust.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("mp_highrise", "https://static.wikia.nocookie.net/callofduty/images/4/49/Highrise-promo.jpg/revision/latest?cb=20100720174411"),
            new Resources.Map("mp_favela", "https://static.wikia.nocookie.net/callofduty/images/2/29/Favela_Map_MW2.jpg/revision/latest?cb=20100720174410"),
            new Resources.Map("mp_nuked", "https://i.ytimg.com/vi/ysr0CyyJx8E/maxresdefault.jpg"),
            new Resources.Map("mp_nightshift", "https://static.wikia.nocookie.net/callofduty/images/d/d2/Skidrow.jpg/revision/latest?cb=20100720174516"),
        ],
        ["IW6"] =
        [
            new Resources.Map("mp_prisonbreak", "https://static.wikia.nocookie.net/callofduty/images/a/a6/Prison_Break_CoDG.jpg/revision/latest?cb=20160123214305"),
            new Resources.Map("mp_dart", "https://static.wikia.nocookie.net/callofduty/images/b/be/Octane_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222225028"),
            new Resources.Map("mp_lonestar", "https://static.wikia.nocookie.net/callofduty/images/2/23/Tremor_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222233807"),
            new Resources.Map("mp_frag", "https://static.wikia.nocookie.net/callofduty/images/e/e4/Freight_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222225820"),
            new Resources.Map("mp_snow", "https://static.wikia.nocookie.net/callofduty/images/9/90/Whiteout_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222234606"),
            new Resources.Map("mp_fahrenheit", "https://static.wikia.nocookie.net/callofduty/images/a/aa/Stormfront_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222233307"),
            new Resources.Map("mp_hashima", "https://static.wikia.nocookie.net/callofduty/images/c/c3/Siege_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222231338"),
            new Resources.Map("mp_warhawk", "https://static.wikia.nocookie.net/callofduty/images/9/97/Warhawk_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222234210"),
            new Resources.Map("mp_sovereign", "https://static.wikia.nocookie.net/callofduty/images/d/de/Sovereign_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222231915"),
            new Resources.Map("mp_zebra", "https://static.wikia.nocookie.net/callofduty/images/8/86/Overlord_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222230253"),
            new Resources.Map("mp_skeleton", "https://static.wikia.nocookie.net/callofduty/images/b/b6/Stonehaven_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222232822"),
            new Resources.Map("mp_chasm", "https://static.wikia.nocookie.net/callofduty/images/f/fe/Chasm_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222201016"),
            new Resources.Map("mp_flooded", "https://static.wikia.nocookie.net/callofduty/images/5/56/Flooded_Menu_Icon_CoDG.jpg/revision/latest?cb=20160222225348"),
            new Resources.Map("mp_strikezone", "https://static.wikia.nocookie.net/callofduty/images/0/02/Strikezone_Menu_Icon_CoDG.jpg/revision/latest?cb=20180514000159"),
            new Resources.Map("mp_descent_new", "https://static.wikia.nocookie.net/callofduty/images/2/21/Free_Fall_Loading_Screen_CoDG.jpg/revision/latest?cb=20160219035443"),
            new Resources.Map("mp_dome_ns", "https://static.wikia.nocookie.net/callofduty/images/8/83/Unearthed_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618191214"),
            new Resources.Map("mp_ca_impact", "https://static.wikia.nocookie.net/callofduty/images/7/77/Collision_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618190921"),
            new Resources.Map("mp_ca_behemoth", "https://static.wikia.nocookie.net/callofduty/images/4/4d/Behemoth_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618190417"),
            new Resources.Map("mp_battery3", "https://static.wikia.nocookie.net/callofduty/images/0/08/Ruins_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618185226"),
            new Resources.Map("mp_dig", "https://static.wikia.nocookie.net/callofduty/images/9/94/Pharaoh_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618191459"),
            new Resources.Map("mp_favela_iw6", "https://static.wikia.nocookie.net/callofduty/images/4/4b/Favela_Map_CoDG.jpg/revision/latest?cb=20150618192317"),
            new Resources.Map("mp_pirate", "https://static.wikia.nocookie.net/callofduty/images/b/b3/Mutiny_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618192100"),
            new Resources.Map("mp_zulu", "https://static.wikia.nocookie.net/callofduty/images/1/14/Departed_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618191721"),
            new Resources.Map("mp_conflict", "https://static.wikia.nocookie.net/callofduty/images/c/cc/Dynasty_Menu_Icon_CoDG.jpg/revision/latest?cb=20160117004931"),
            new Resources.Map("mp_mine", "https://static.wikia.nocookie.net/callofduty/images/9/9d/Goldrush_Nemesis_CoDG.jpg/revision/latest?cb=20160117231327"),
            new Resources.Map("mp_shipment_ns", "https://static.wikia.nocookie.net/callofduty/images/f/f5/Showtime_Menu_Icon_CoDG.png/revision/latest?cb=20160117030703"),
            new Resources.Map("mp_zerosub", "https://static.wikia.nocookie.net/callofduty/images/f/f2/Subzero_Nemesis_CoDG.jpg/revision/latest?cb=20160117230851"),
            new Resources.Map("mp_boneyard_ns", "https://static.wikia.nocookie.net/callofduty/images/8/87/Ignition_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618184639"),
            new Resources.Map("mp_ca_red_river", "https://static.wikia.nocookie.net/callofduty/images/9/93/Containment_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618184139"),
            new Resources.Map("mp_ca_rumble", "https://static.wikia.nocookie.net/callofduty/images/2/2b/BayView_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618183749"),
            new Resources.Map("mp_swamp", "https://static.wikia.nocookie.net/callofduty/images/5/56/Fog_Loading_Screen_CoDG.jpg/revision/latest?cb=20150618183104"),
            new Resources.Map("mp_alien_town", "https://static.wikia.nocookie.net/callofduty/images/a/a9/Point_of_Contact_loading_screen_CoDG.png/revision/latest?cb=20140818190238"),
            new Resources.Map("mp_alien_armory", "https://static.wikia.nocookie.net/callofduty/images/3/3b/Nightfall_Screenshot_CoDG.jpg/revision/latest?cb=20170705221821"),
            new Resources.Map("mp_alien_beacon", "https://static.wikia.nocookie.net/callofduty/images/f/f2/Mayday_CoDG.jpg/revision/latest?cb=20160117211635"),
            new Resources.Map("mp_alien_dlc3", "https://static.wikia.nocookie.net/callofduty/images/5/52/CoDG_Invasion_Extinction_Awakening_o.jpg/revision/latest?cb=20140605021520"),
            new Resources.Map("mp_alien_last", "https://static.wikia.nocookie.net/callofduty/images/d/db/Exodus_CoDG.jpg/revision/latest?cb=20160117203311"),
        ],
        ["T4"] =
        [
            new Resources.Map("mp_airfield", "https://static.wikia.nocookie.net/callofduty/images/0/04/Airfield.jpg/revision/latest?cb=20100703083537"),
            new Resources.Map("mp_asylum", "https://static.wikia.nocookie.net/callofduty/images/9/99/Asylum.jpg/revision/latest?cb=20100703075737"),
            new Resources.Map("mp_castle", "https://static.wikia.nocookie.net/callofduty/images/e/e1/Castle.jpg/revision/latest?cb=20100703075702"),
            new Resources.Map("mp_shrine", "https://static.wikia.nocookie.net/callofduty/images/b/b5/Cliffside.jpg/revision/latest?cb=20110702030241"),
            new Resources.Map("mp_courtyard", "https://static.wikia.nocookie.net/callofduty/images/3/30/Courtyard.jpg/revision/latest?cb=20100703075822"),
            new Resources.Map("mp_dome", "https://static.wikia.nocookie.net/callofduty/images/6/64/Dome.jpg/revision/latest?cb=20100703075919"),
            new Resources.Map("mp_downfall", "https://static.wikia.nocookie.net/callofduty/images/0/03/Downfall_Loadscreen_WaW.png/revision/latest?cb=20121128143425"),
            new Resources.Map("mp_hangar", "https://static.wikia.nocookie.net/callofduty/images/b/be/Hanger.jpg/revision/latest?cb=20100703080146"),
            new Resources.Map("mp_makin", "https://static.wikia.nocookie.net/callofduty/images/f/fa/Makin.jpg/revision/latest?cb=20110710131317"),
            new Resources.Map("mp_outskirts", "https://static.wikia.nocookie.net/callofduty/images/4/44/Outskirts.jpg/revision/latest?cb=20100703080341"),
            new Resources.Map("mp_roundhouse", "https://static.wikia.nocookie.net/callofduty/images/2/25/Roundhouse.jpg/revision/latest?cb=20100703080407"),
            new Resources.Map("mp_suburban", "https://static.wikia.nocookie.net/callofduty/images/f/fb/Upheaval.jpg/revision/latest?cb=20100703081123"),
            new Resources.Map("mp_kneedeep", "https://static.wikia.nocookie.net/callofduty/images/d/d1/KneeDeepLoad.jpg/revision/latest?cb=20100703075448"),
            new Resources.Map("mp_nachtfeuer", "https://static.wikia.nocookie.net/callofduty/images/7/73/Nightfire.jpg/revision/latest?cb=20100703081308"),
            new Resources.Map("mp_subway", "https://static.wikia.nocookie.net/callofduty/images/6/6f/Station.jpg/revision/latest?cb=20100703081515"),
            new Resources.Map("mp_kwai", "https://static.wikia.nocookie.net/callofduty/images/d/de/Banzaiscreenshot.jpg/revision/latest?cb=20100703081611"),
            new Resources.Map("mp_stalingrad", "https://static.wikia.nocookie.net/callofduty/images/5/58/Corrosionscreenshot.jpg/revision/latest?cb=20100703081643"),
            new Resources.Map("mp_docks", "https://static.wikia.nocookie.net/callofduty/images/5/50/Subpensscreenshot.jpg/revision/latest?cb=20100703081718"),
            new Resources.Map("mp_drum", "https://static.wikia.nocookie.net/callofduty/images/3/30/Battery.jpg/revision/latest?cb=20100703081836"),
            new Resources.Map("mp_bgate", "https://static.wikia.nocookie.net/callofduty/images/9/9e/Breach.jpg/revision/latest?cb=20100703082957"),
            new Resources.Map("mp_vodka", "https://static.wikia.nocookie.net/callofduty/images/f/f3/Revolution.jpg/revision/latest?cb=20100703083210"),
            new Resources.Map("nazi_zombie_prototype", "https://static.wikia.nocookie.net/callofduty/images/2/2b/Nacht_Der_Untoten_Menu_Selection_WaW.png/revision/latest?cb=20161009103531"),
            new Resources.Map("nazi_zombie_asylum", "https://static.wikia.nocookie.net/callofduty/images/a/a1/Verruckt_Menu_Selection_WaW.png/revision/latest?cb=20161009103542"),
            new Resources.Map("nazi_zombie_sumpf", "https://static.wikia.nocookie.net/callofduty/images/2/2f/Shi_No_Numa_Menu_Selection_WaW.png/revision/latest?cb=20161009103553"),
            new Resources.Map("nazi_zombie_factory", "https://static.wikia.nocookie.net/callofduty/images/8/86/Der_Riese_Menu_Selection_WaW.png/revision/latest?cb=20161009103603"),
        ],
        ["T5"] =
        [
            new Resources.Map("mp_array", "https://static.wikia.nocookie.net/callofduty/images/3/35/Bare_Load_Screen_Array_BO.jpg/revision/latest?cb=20110303121651"),
            new Resources.Map("mp_berlinwall2", "https://static.wikia.nocookie.net/callofduty/images/7/78/Berlin_Wall_loadscreen_BO.jpg/revision/latest?cb=20121108093747"),
            new Resources.Map("mp_gridlock", "https://static.wikia.nocookie.net/callofduty/images/7/7a/Recreated_Load_Screen_Convoy_BO.jpg/revision/latest?cb=20110606062753"),
            new Resources.Map("mp_cracked", "https://static.wikia.nocookie.net/callofduty/images/1/1e/Bare_Load_Screen_Cracked_BO.jpg/revision/latest?cb=20110303121738"),
            new Resources.Map("mp_crisis", "https://static.wikia.nocookie.net/callofduty/images/f/f6/Bare_Load_Screen_Crisis_BO.jpg/revision/latest?cb=20110303121824"),
            new Resources.Map("mp_discovery", "https://static.wikia.nocookie.net/callofduty/images/0/09/Discovery_loadscreen_BO.jpg/revision/latest?cb=20121108094733"),
            new Resources.Map("mp_drivein", "https://static.wikia.nocookie.net/callofduty/images/9/9e/Galactic_Sign_Drive-In_BO.png/revision/latest?cb=20120118175649"),
            new Resources.Map("mp_firingrange", "https://static.wikia.nocookie.net/callofduty/images/8/82/Bare_Load_Screen_Firing_Range_BO.jpg/revision/latest?cb=20110303121918"),
            new Resources.Map("mp_duga", "https://static.wikia.nocookie.net/callofduty/images/4/41/Bare_Load_Screen_Grid_BO.jpg/revision/latest?cb=20110303122000"),
            new Resources.Map("mp_area51", "https://static.wikia.nocookie.net/callofduty/images/a/a2/Hangar_18_loadscreen_BO.png/revision/latest?cb=20130714193416"),
            new Resources.Map("mp_hanoi", "https://static.wikia.nocookie.net/callofduty/images/e/eb/Bare_Load_Screen_Hanoi_BO.jpg/revision/latest?cb=20110303122041"),
            new Resources.Map("mp_cairo", "https://static.wikia.nocookie.net/callofduty/images/e/e7/Bare_Load_Screen_Havana_BO.jpg/revision/latest?cb=20110303122124"),
            new Resources.Map("mp_golfcourse", "https://static.wikia.nocookie.net/callofduty/images/4/48/Overview_Hazard_BO.png/revision/latest?cb=20120119064515"),
            new Resources.Map("mp_hotel", "https://static.wikia.nocookie.net/callofduty/images/c/ca/Bare_Load_Screen_Hotel_BO.png/revision/latest?cb=20110617143724"),
            new Resources.Map("mp_havoc", "https://static.wikia.nocookie.net/callofduty/images/c/c6/Bare_Load_Screen_Jungle_BO.jpg/revision/latest?cb=20110303122217"),
            new Resources.Map("mp_kowloon", "https://static.wikia.nocookie.net/callofduty/images/a/a7/Kowloon_loadscreen_BO.jpg/revision/latest?cb=20121108094415"),
            new Resources.Map("mp_cosmodrome", "https://static.wikia.nocookie.net/callofduty/images/c/c6/Bare_Load_Screen_Launch_BO.jpg/revision/latest?cb=20110303122251"),
            new Resources.Map("mp_nuked", "https://i.ytimg.com/vi/ysr0CyyJx8E/maxresdefault.jpg"),
            new Resources.Map("mp_radiation", "https://static.wikia.nocookie.net/callofduty/images/2/20/Bare_Load_Screen_Radiation_BO.jpg/revision/latest?cb=20110303122417"),
            new Resources.Map("mp_silo", "https://static.wikia.nocookie.net/callofduty/images/a/a7/Warhead_Silo_BO.png/revision/latest?cb=20120121223541"),
            new Resources.Map("mp_stadium", "https://static.wikia.nocookie.net/callofduty/images/2/24/Stadium_loadscreen_BO.jpg/revision/latest?cb=20121108092948"),
            new Resources.Map("mp_outskirts", "https://static.wikia.nocookie.net/callofduty/images/2/2d/Bare_Load_Screen_Stockpile_BO.jpg/revision/latest?cb=20110605094802"),
            new Resources.Map("mp_mountain", "https://static.wikia.nocookie.net/callofduty/images/5/54/Bare_Load_Screen_Summit_BO.jpg/revision/latest?cb=20110303122702"),
            new Resources.Map("mp_villa", "https://static.wikia.nocookie.net/callofduty/images/2/2a/Bare_Load_Screen_Villa_BO.jpg/revision/latest?cb=20110303122503"),
            new Resources.Map("mp_russianbase", "https://static.wikia.nocookie.net/callofduty/images/1/12/Bare_Load_Screen_WMD_BO.jpg/revision/latest?cb=20110303122544"),
            new Resources.Map("mp_zoo", "https://static.wikia.nocookie.net/callofduty/images/7/78/Recreated_Load_Screen_Zoo_BO.jpg/revision/latest?cb=20110606065905"),
        ],
        ["T6"] =
        [
            new Resources.Map("mp_la", "https://static.wikia.nocookie.net/callofduty/images/b/ba/Aftermath_loading_screen_BOII.png/revision/latest?cb=20130125112538"),
            new Resources.Map("mp_dockside", "https://static.wikia.nocookie.net/callofduty/images/d/d4/Cargo_loadscreen_BOII.png/revision/latest?cb=20130120072815"),
            new Resources.Map("mp_carrier", "https://static.wikia.nocookie.net/callofduty/images/8/88/Carrier_loadscreen_BOII.png/revision/latest?cb=20121209072436"),
            new Resources.Map("mp_drone", "https://static.wikia.nocookie.net/callofduty/images/5/5b/Drone_loadscreen_BOII.png/revision/latest?cb=20121209074205"),
            new Resources.Map("mp_express", "https://static.wikia.nocookie.net/callofduty/images/d/d1/Express_Load_Screen_BOII.png/revision/latest?cb=20121209074544"),
            new Resources.Map("mp_hijacked", "https://static.wikia.nocookie.net/callofduty/images/7/79/Hijacked_Load_Screen_BOII.png/revision/latest?cb=20121209075028"),
            new Resources.Map("mp_meltdown", "https://static.wikia.nocookie.net/callofduty/images/9/92/Meltdown_Load_Screen_BOII.png/revision/latest?cb=20121209075341"),
            new Resources.Map("mp_overflow", "https://static.wikia.nocookie.net/callofduty/images/8/80/Overflow_Load_Screen_BOII.png/revision/latest?cb=20121209075750"),
            new Resources.Map("mp_nightclub", "https://static.wikia.nocookie.net/callofduty/images/7/74/Plaza_Load_Screen_BOII.png/revision/latest?cb=20130125112602"),
            new Resources.Map("mp_raid", "https://static.wikia.nocookie.net/callofduty/images/2/29/Raid_Load_Screen_BOII.png/revision/latest?cb=20121209080157"),
            new Resources.Map("mp_slums", "https://static.wikia.nocookie.net/callofduty/images/0/04/Slums_Load_Screen_BOII.png/revision/latest?cb=20121209080826"),
            new Resources.Map("mp_village", "https://static.wikia.nocookie.net/callofduty/images/1/1f/Standoff_Load_Screen_BOII.png/revision/latest?cb=20121209080838"),
            new Resources.Map("mp_turbine", "https://static.wikia.nocookie.net/callofduty/images/5/50/Turbine_Load_Screen_BOII.png/revision/latest?cb=20121209081207"),
            new Resources.Map("mp_socotra", "https://static.wikia.nocookie.net/callofduty/images/6/6d/Yemen_Load_Screen_BOII.png/revision/latest?cb=20121209071959"),
            new Resources.Map("mp_nuketown_2020", "https://static.wikia.nocookie.net/callofduty/images/0/03/Nuketown_2025_Load_Screen_BOII.png/revision/latest?cb=20121217102325"),
            new Resources.Map("mp_downhill", "https://static.wikia.nocookie.net/callofduty/images/2/28/Downhill_In-Game.jpg/revision/latest?cb=20130201205402"),
            new Resources.Map("mp_mirage", "https://static.wikia.nocookie.net/callofduty/images/d/d3/Mirage_loadscreen_BOII.png/revision/latest?cb=20140426185229"),
            new Resources.Map("mp_hydro", "https://static.wikia.nocookie.net/callofduty/images/4/44/Hydro_In-Game.jpg/revision/latest?cb=20130201204341"),
            new Resources.Map("mp_skate", "https://static.wikia.nocookie.net/callofduty/images/8/86/Grind_In-Game.jpg/revision/latest?cb=20130201203728"),
            new Resources.Map("mp_concert", "https://static.wikia.nocookie.net/callofduty/images/4/4d/Encore_loadscreen_BOII.png/revision/latest?cb=20130905100408"),
            new Resources.Map("mp_magma", "https://static.wikia.nocookie.net/callofduty/images/3/30/Magma_loadscreen_BOII.png/revision/latest?cb=20130905100136"),
            new Resources.Map("mp_vertigo", "https://static.wikia.nocookie.net/callofduty/images/f/f6/Vertigo_loadscreen_BOII.png/revision/latest?cb=20130905095457"),
            new Resources.Map("mp_studio", "https://static.wikia.nocookie.net/callofduty/images/1/1e/Studio_loadscreen_BOII.png/revision/latest?cb=20130905095718"),
            new Resources.Map("mp_uplink", "https://static.wikia.nocookie.net/callofduty/images/f/fc/Uplink_loadscreen_BOII.png/revision/latest?cb=20130905095254"),
            new Resources.Map("mp_bridge", "https://static.wikia.nocookie.net/callofduty/images/0/04/Detour_loadscreen_BOII.png/revision/latest?cb=20130905095021"),
            new Resources.Map("mp_castaway", "https://static.wikia.nocookie.net/callofduty/images/e/ee/Cove_loadscreen_BOII.png/revision/latest?cb=20130905100640"),
            new Resources.Map("mp_paintball", "https://static.wikia.nocookie.net/callofduty/images/2/2e/Rush_loadscreen_BOII.png/revision/latest?cb=20130905095938"),
            new Resources.Map("mp_dig", "https://static.wikia.nocookie.net/callofduty/images/8/83/Dig_loadscreen_BOII.png/revision/latest?cb=20140426105014"),
            new Resources.Map("mp_frostbite", "https://static.wikia.nocookie.net/callofduty/images/4/43/Frost_loadscreen_BOII.png/revision/latest?cb=20140426105546"),
            new Resources.Map("mp_pod", "https://static.wikia.nocookie.net/callofduty/images/4/42/Pod_loadscreen_BOII.png/revision/latest?cb=20140426105842"),
            new Resources.Map("mp_takeoff", "https://static.wikia.nocookie.net/callofduty/images/3/3f/Takeoff_loadscreen_BOII.png/revision/latest?cb=20140426110209"),
            new Resources.Map("zm_buried", "https://static.wikia.nocookie.net/callofduty/images/7/71/Buried_menu_BOII.png/revision/latest?cb=20161102222409"),
            new Resources.Map("zm_highrise", "https://static.wikia.nocookie.net/callofduty/images/6/60/Die_Rise_menu_selection_BO2.png/revision/latest?cb=20161102222915"),
            new Resources.Map("zm_nuked", "https://static.wikia.nocookie.net/callofduty/images/7/74/Nuketown_menu_selection_BO2.png/revision/latest?cb=20161102222934"),
            new Resources.Map("zm_prison", "https://static.wikia.nocookie.net/callofduty/images/a/aa/Mob_of_the_Dead_menu_selection_BO2.png/revision/latest?cb=20161102222825"),
            new Resources.Map("zm_tomb", "https://static.wikia.nocookie.net/callofduty/images/b/b2/Origins_Lobby_Icon_BO2.png/revision/latest?cb=20161102222425"),
            new Resources.Map("zm_transit_dr", "https://static.wikia.nocookie.net/callofduty/images/b/b4/Diner_TranZit_BOII.png/revision/latest?cb=20130224071848"),
            new Resources.Map("zm_transit", "https://static.wikia.nocookie.net/callofduty/images/f/f9/TranZit_lobby_BOII.png/revision/latest?cb=20161102222339"),
        ],
        ["T7"] =
        [
            new Resources.Map("mp_apartments", "https://static.wikia.nocookie.net/callofduty/images/4/41/Evac_Map_Preview_BO3.png/revision/latest?cb=20200804015812"),
            new Resources.Map("mp_biodome", "https://static.wikia.nocookie.net/callofduty/images/a/a8/Aquarium_Map_Preview_BO3.png/revision/latest?cb=20200804014624"),
            new Resources.Map("mp_chinatown", "https://static.wikia.nocookie.net/callofduty/images/a/aa/Exodus_Map_Preview_BO3.png/revision/latest?cb=20200804015813"),
            new Resources.Map("mp_ethiopia", "https://static.wikia.nocookie.net/callofduty/images/5/50/Hunted_menu_icon_BO3.jpg/revision/latest?cb=20180311204011"),
            new Resources.Map("mp_havoc", "https://static.wikia.nocookie.net/callofduty/images/1/17/Havoc_Map_Preview_BO3.png/revision/latest?cb=20200804002228"),
            new Resources.Map("mp_infection", "https://static.wikia.nocookie.net/callofduty/images/9/9a/Infection_Map_Preview_BO3.png/revision/latest?cb=20200804015817"),
            new Resources.Map("mp_metro", "https://static.wikia.nocookie.net/callofduty/images/6/60/Metro_Map_Preview_BO3.png/revision/latest?cb=20200804015818"),
            new Resources.Map("mp_redwood", "https://static.wikia.nocookie.net/callofduty/images/1/18/Redwood_Map_Preview_BO3.png/revision/latest?cb=20200804015819"),
            new Resources.Map("mp_sector", "https://static.wikia.nocookie.net/callofduty/images/7/7e/Combine_Map_Preview_BO3.png/revision/latest?cb=20200804015811"),
            new Resources.Map("mp_spire", "https://static.wikia.nocookie.net/callofduty/images/e/e8/Breach_Map_Preview_BO3.png/revision/latest?cb=20200804015810"),
            new Resources.Map("mp_stronghold", "https://static.wikia.nocookie.net/callofduty/images/4/42/Stronghold_Map_Preview_BO3.png/revision/latest?cb=20200804022135"),
            new Resources.Map("mp_veiled", "https://static.wikia.nocookie.net/callofduty/images/e/ee/Fringe_Map_Preview_BO3.png/revision/latest?cb=20200804015814"),
            new Resources.Map("mp_nuketown_x", "https://static.wikia.nocookie.net/callofduty/images/e/ef/Nuk3town_menu_icon_BO3.jpg/revision/latest?cb=20180523201916"),
            new Resources.Map("mp_crucible", "https://static.wikia.nocookie.net/callofduty/images/7/79/Gauntlet_Loading_Screen_BO3.png/revision/latest?cb=20160131214452"),
            new Resources.Map("mp_rise", "https://static.wikia.nocookie.net/callofduty/images/7/79/Rise_Loading_Screen_BO3.png/revision/latest?cb=20160131214729"),
            new Resources.Map("mp_skyjacked", "https://static.wikia.nocookie.net/callofduty/images/4/4d/Skyjacked_menu_icon_BO3.jpg/revision/latest?cb=20180523010428"),
            new Resources.Map("mp_waterpark", "https://static.wikia.nocookie.net/callofduty/images/e/e0/Splash_Loading_Screen_BO3.png/revision/latest?cb=20160131214058"),
            new Resources.Map("mp_aerospace", "https://static.wikia.nocookie.net/callofduty/images/4/47/Spire_menu_icon_BO3.jpg/revision/latest?cb=20180523013350"),
            new Resources.Map("mp_banzai", "https://static.wikia.nocookie.net/callofduty/images/1/12/Verge_menu_icon_BO3.jpg/revision/latest?cb=20180523011351"),
            new Resources.Map("mp_conduit", "https://static.wikia.nocookie.net/callofduty/images/5/59/Rift_menu_icon_BO3.jpg/revision/latest?cb=20180523205348"),
            new Resources.Map("mp_kung_fu", "https://static.wikia.nocookie.net/callofduty/images/6/6e/Knockout_menu_icon_BO3.jpg/revision/latest?cb=20180523012843"),
            new Resources.Map("mp_arena", "https://static.wikia.nocookie.net/callofduty/images/f/f9/Rumble_menu_icon_BO3.jpg/revision/latest?cb=20180311222050"),
            new Resources.Map("mp_cryogen", "https://static.wikia.nocookie.net/callofduty/images/d/da/Screen_Shot_2018-03-27_at_15.26.07.png/revision/latest?cb=20180401121336"),
            new Resources.Map("mp_rome", "https://static.wikia.nocookie.net/callofduty/images/8/80/Empire_Map_Icon_BOIII.jpg/revision/latest?cb=20160812181614"),
            new Resources.Map("mp_shrine", "https://static.wikia.nocookie.net/callofduty/images/f/fc/Screen_Shot_2018-04-01_at_13.43.54.png/revision/latest?cb=20180401124753"),
            new Resources.Map("mp_city", "https://static.wikia.nocookie.net/callofduty/images/0/0e/Rupture_BOIII.jpeg/revision/latest?cb=20160825190008"),
            new Resources.Map("mp_miniature", "https://static.wikia.nocookie.net/callofduty/images/e/e1/Micro_Loading_Screen_BO3.png/revision/latest?cb=20170612151647"),
            new Resources.Map("mp_ruins", "https://static.wikia.nocookie.net/callofduty/images/c/cc/Screen_Shot_2018-04-01_at_13.44.50.png/revision/latest?cb=20180401143041"),
            new Resources.Map("mp_western", "https://static.wikia.nocookie.net/callofduty/images/2/25/Outlaw_BOIII.jpeg/revision/latest?cb=20160825185938"),
            new Resources.Map("zm_zod", "https://static.wikia.nocookie.net/callofduty/images/1/14/Shadows_of_Evil_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20160923082206"),
            new Resources.Map("zm_castle", "https://static.wikia.nocookie.net/callofduty/images/e/e4/Der_Eisendrache_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20160923082230"),
            new Resources.Map("zm_island", "https://static.wikia.nocookie.net/callofduty/images/0/06/Zetsubou_No_Shima_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20160923082244"),
            new Resources.Map("zm_stalingrad", "https://static.wikia.nocookie.net/callofduty/images/7/72/Gorod_Krovi_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20160923082253"),
            new Resources.Map("zm_gensis", "https://static.wikia.nocookie.net/callofduty/images/d/de/Revelations_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20161007033102"),
            new Resources.Map("zm_cosmodrome", "https://static.wikia.nocookie.net/callofduty/images/d/d8/Ascension_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042103"),
            new Resources.Map("zm_theater", "https://static.wikia.nocookie.net/callofduty/images/e/ec/Kino_Der_Toten_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042116"),
            new Resources.Map("zm_moon", "https://static.wikia.nocookie.net/callofduty/images/4/4a/Moon_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042150"),
            new Resources.Map("zm_prototype", "https://static.wikia.nocookie.net/callofduty/images/6/64/Nacht_Der_Untoten_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042202"),
            new Resources.Map("zm_tomb", "https://static.wikia.nocookie.net/callofduty/images/0/09/Origins_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042215"),
            new Resources.Map("zm_temple", "https://static.wikia.nocookie.net/callofduty/images/7/76/Shangri_La_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042246"),
            new Resources.Map("zm_sumpf", "https://static.wikia.nocookie.net/callofduty/images/1/16/Shi_No_Numa_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042257"),
            new Resources.Map("zm_factory", "https://static.wikia.nocookie.net/callofduty/images/4/4d/The_Giant_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20160923082219"),
            new Resources.Map("zm_asylum", "https://static.wikia.nocookie.net/callofduty/images/e/e4/Verruckt_Menu_Selection_BO3.png/revision/latest/scale-to-width-down/1000?cb=20170617042321"),
        ],
        ["SHG1"] =
        [
            new Resources.Map("mp_refraction", "https://static.wikia.nocookie.net/callofduty/images/a/a5/Ascend_loading_screen_AW.png/revision/latest?cb=20150402170105"),
            new Resources.Map("mp_lab2", "https://static.wikia.nocookie.net/callofduty/images/e/e7/Bio_Lab_loading_screen_AW.png/revision/latest?cb=20150402164955"),
            new Resources.Map("mp_comeback", "https://static.wikia.nocookie.net/callofduty/images/a/a3/Comeback_loading_screen_AW.png/revision/latest?cb=20150402170220"),
            new Resources.Map("mp_laser2", "https://static.wikia.nocookie.net/callofduty/images/c/c2/Defender_Map_AW.png/revision/latest?cb=20150125135028"),
            new Resources.Map("mp_detroit", "https://static.wikia.nocookie.net/callofduty/images/c/cb/Detroit_Map_AW.png/revision/latest?cb=20150125135608"),
            new Resources.Map("mp_greenband", "https://static.wikia.nocookie.net/callofduty/images/6/63/Greenband_loading_screen_AW.png/revision/latest?cb=20150402170141"),
            new Resources.Map("mp_levity", "https://static.wikia.nocookie.net/callofduty/images/7/76/Horizon_loading_screen_AW.png/revision/latest?cb=20150402165803"),
            new Resources.Map("mp_instinct", "https://static.wikia.nocookie.net/callofduty/images/7/73/Instinct_Map_AW.png/revision/latest?cb=20150125135946"),
            new Resources.Map("mp_recovery", "https://static.wikia.nocookie.net/callofduty/images/f/f1/Recovery_Map_AW.png/revision/latest?cb=20150125140230"),
            new Resources.Map("mp_venus", "https://static.wikia.nocookie.net/callofduty/images/a/aa/Retreat_loading_screen_AW.png/revision/latest?cb=20150402170027"),
            new Resources.Map("mp_prison", "https://static.wikia.nocookie.net/callofduty/images/2/2e/Riot_Map_AW.png/revision/latest?cb=20150125140554"),
            new Resources.Map("mp_solar", "https://static.wikia.nocookie.net/callofduty/images/6/65/Solar_Map_AW.png/revision/latest?cb=20150125140854"),
            new Resources.Map("mp_terrace", "https://static.wikia.nocookie.net/callofduty/images/1/10/Terrace_loading_screen_AW.png/revision/latest?cb=20150402165845"),
            new Resources.Map("mp_dam", "https://static.wikia.nocookie.net/callofduty/images/4/46/Atlas_Gorge_Map_AW.png/revision/latest?cb=20150125134232"),
            new Resources.Map("mp_spark", "https://static.wikia.nocookie.net/callofduty/images/2/20/Chop_Shop_Environment_AW.png/revision/latest?cb=20150429185159"),
            new Resources.Map("mp_climate_3", "https://static.wikia.nocookie.net/callofduty/images/8/85/Climate_Environment_AW.png/revision/latest?cb=20150429183851"),
            new Resources.Map("mp_sector17", "https://static.wikia.nocookie.net/callofduty/images/e/ea/Compound_Promo_AW.png/revision/latest?cb=20150526191037"),
            new Resources.Map("mp_lost", "https://static.wikia.nocookie.net/callofduty/images/7/7a/Core_Environment_AW.jpg/revision/latest?cb=20150116234301"),
            new Resources.Map("mp_torqued", "https://static.wikia.nocookie.net/callofduty/images/2/2a/Drift_Environment_AW.jpg/revision/latest?cb=20150116234625"),
            new Resources.Map("mp_fracture", "https://static.wikia.nocookie.net/callofduty/images/5/58/Fracture_Loading_Screen_AW.png/revision/latest?cb=20161128124952"),
            new Resources.Map("mp_kremlin", "https://static.wikia.nocookie.net/callofduty/images/9/99/Kremlin_Loading_Screen_AW.png/revision/latest?cb=20161128125546"),
            new Resources.Map("mp_lair", "https://static.wikia.nocookie.net/callofduty/images/f/f2/Overload_Loading_Screen_AW.png/revision/latest?cb=20161128115756"),
            new Resources.Map("mp_bigben2", "https://static.wikia.nocookie.net/callofduty/images/4/46/Parliament_Loading_Screen_AW.png/revision/latest?cb=20161128125556"),
            new Resources.Map("mp_perplex_1", "https://static.wikia.nocookie.net/callofduty/images/d/d9/Perplex_Environment_AW.png/revision/latest?cb=20150429181437"),
            new Resources.Map("mp_liberty", "https://static.wikia.nocookie.net/callofduty/images/7/7c/Quarantine_Loading_Screen_AW.png/revision/latest?cb=20160214220724"),
            new Resources.Map("mp_clowntown3", "https://static.wikia.nocookie.net/callofduty/images/4/45/Sideshow_Environment_AW.jpg/revision/latest?cb=20150116234923"),
            new Resources.Map("mp_blackbox", "https://static.wikia.nocookie.net/callofduty/images/1/14/Site_244_Environment_AW.png/revision/latest?cb=20150429183525"),
            new Resources.Map("mp_highrise2", "https://static.wikia.nocookie.net/callofduty/images/d/db/Skyrise_Loading_Screen_AW.png/revision/latest?cb=20161128125606"),
            new Resources.Map("mp_seoul2", "https://static.wikia.nocookie.net/callofduty/images/e/e2/Swarm_artwork_AW.png/revision/latest?cb=20150727184217"),
            new Resources.Map("mp_urban", "https://static.wikia.nocookie.net/callofduty/images/5/52/Urban_Environment_AW.jpg/revision/latest?cb=20150116235245"),
            new Resources.Map("mp_zombie_ark", "https://static.wikia.nocookie.net/callofduty/images/d/db/Outbreak_Environment_AW.jpg/revision/latest?cb=20150116235718"),
            new Resources.Map("mp_zombie_brg", "https://static.wikia.nocookie.net/callofduty/images/2/2e/Infection_environment_AW.jpg/revision/latest?cb=20150318181252"),
            new Resources.Map("mp_zombie_h2o", "https://static.wikia.nocookie.net/callofduty/images/b/bd/Carrier_Ingame_Icon_AW.jpg/revision/latest?cb=20180805025428"),
            new Resources.Map("mp_zombie_lab", "https://static.wikia.nocookie.net/callofduty/images/d/d9/ExoZombies_Descent_AW.jpg/revision/latest?cb=20150803181055"),
        ],
        ["CSGO"] =
        [
            new Resources.Map("ar_baggage", "https://static.wikia.nocookie.net/cswikia/images/3/35/Csgo_ar_baggage.png/revision/latest/scale-to-width-down/1000?cb=20120422195558"),
            new Resources.Map("ar_dizzy", "https://static.wikia.nocookie.net/cswikia/images/2/20/Ar_dizzy_thumbnail.jpg/revision/latest/scale-to-width-down/1000?cb=20170610032801"),
            new Resources.Map("ar_lunacy", "https://static.wikia.nocookie.net/cswikia/images/c/ca/Ar_lunacy.png/revision/latest/scale-to-width-down/1000?cb=20191119180902"),
            new Resources.Map("ar_monastery", "https://static.wikia.nocookie.net/cswikia/images/e/e1/Ar_monastery.png/revision/latest/scale-to-width-down/1000?cb=20201203223644"),
            new Resources.Map("ar_shoots", "https://static.wikia.nocookie.net/cswikia/images/2/23/Shoots-overview.png/revision/latest/scale-to-width-down/1000?cb=20210831221835"),
            new Resources.Map("cs_agency", "https://static.wikia.nocookie.net/cswikia/images/c/c7/Cs_agency_thumbnail.jpg/revision/latest/scale-to-width-down/1000?cb=20170610042527"),
            new Resources.Map("cs_assault", "https://static.wikia.nocookie.net/cswikia/images/0/00/Cs_assault_go.png/revision/latest/scale-to-width-down/1000?cb=20140819095651"),
            new Resources.Map("cs_italy", "https://static.wikia.nocookie.net/cswikia/images/2/2c/Cs_italy_csgo.png/revision/latest/scale-to-width-down/1000?cb=20140819100829"),
            new Resources.Map("cs_militia", "https://static.wikia.nocookie.net/cswikia/images/2/2b/Csgo_militia_pic1.jpg/revision/latest/scale-to-width-down/1000?cb=20190123130803"),
            new Resources.Map("cs_office", "https://static.wikia.nocookie.net/cswikia/images/f/f7/Csgo-cs-office.png/revision/latest/scale-to-width-down/1000?cb=20140820132335"),
            new Resources.Map("de_ancient", "https://static.wikia.nocookie.net/cswikia/images/9/94/De_ancient.png/revision/latest/scale-to-width-down/1000?cb=20201204072600"),
            new Resources.Map("de_bank", "https://static.wikia.nocookie.net/cswikia/images/a/a9/Csgo-de-bank.png/revision/latest/scale-to-width-down/1000?cb=20140820131729"),
            new Resources.Map("de_cache", "https://static.wikia.nocookie.net/cswikia/images/5/5b/De_cache.png/revision/latest/scale-to-width-down/1000?cb=20200415102625"),
            new Resources.Map("de_calavera", "https://static.wikia.nocookie.net/cswikia/images/2/24/EozeThnXYAouxrf.jpg/revision/latest/scale-to-width-down/1000?cb=20210116194812"),
            new Resources.Map("de_canals", "https://static.wikia.nocookie.net/cswikia/images/5/56/De_canals_thumbnail.jpg/revision/latest/scale-to-width-down/1000?cb=20170316114745"),
            new Resources.Map("de_cbble", "https://static.wikia.nocookie.net/cswikia/images/f/f1/De_cbble_loading_screen.jpg/revision/latest/scale-to-width-down/1000?cb=20210828112634"),
            new Resources.Map("de_dust2", "https://static.wikia.nocookie.net/cswikia/images/4/42/Dust2_asite1.png/revision/latest/scale-to-width-down/1000?cb=20211006143721"),
            new Resources.Map("de_grind", "https://static.wikia.nocookie.net/cswikia/images/d/da/Csgo_grind_map.jpg/revision/latest/scale-to-width-down/1000?cb=20210515220952"),
            new Resources.Map("de_inferno", "https://static.wikia.nocookie.net/cswikia/images/f/f0/Inferno.jpg/revision/latest/scale-to-width-down/1000?cb=20161014013320"),
            new Resources.Map("de_lake", "https://static.wikia.nocookie.net/cswikia/images/0/08/Csgo-de-lake.png/revision/latest/scale-to-width-down/1000?cb=20140820130934"),
            new Resources.Map("de_mirage", "https://static.wikia.nocookie.net/cswikia/images/1/1e/CSGO_Mirage_latest_version.jpg/revision/latest/scale-to-width-down/1000?cb=20200301201524"),
            new Resources.Map("de_mocha", "https://static.wikia.nocookie.net/cswikia/images/0/0b/Csgo_map_Mocha.jpg/revision/latest/scale-to-width-down/1000?cb=20210519213544"),
            new Resources.Map("de_nuke", "https://static.wikia.nocookie.net/cswikia/images/9/93/CSGO_Nuke_22_Nov_2019_update_picture_1.jpg/revision/latest/scale-to-width-down/1000?cb=20210903110157"),
            new Resources.Map("de_overpass", "https://static.wikia.nocookie.net/cswikia/images/6/6e/Csgo-de-overpass.png/revision/latest/scale-to-width-down/1000?cb=20140820130544"),
            new Resources.Map("de_pitstop", "https://static.wikia.nocookie.net/cswikia/images/c/c6/Csgo_map_Pitstop.jpg/revision/latest/scale-to-width-down/1000?cb=20210526194248"),
            new Resources.Map("de_safehouse", "https://static.wikia.nocookie.net/cswikia/images/2/27/Csgo-de-safehouse.png/revision/latest/scale-to-width-down/1000?cb=20140820130431"),
            new Resources.Map("de_shortdust", "https://static.wikia.nocookie.net/cswikia/images/7/70/Csgo-shortdust-mid.png/revision/latest/scale-to-width-down/1000?cb=20141113033209"),
            new Resources.Map("de_shortnuke", "https://static.wikia.nocookie.net/cswikia/images/8/8b/De_shortnuke.jpg/revision/latest/scale-to-width-down/1000?cb=20180421181417"),
            new Resources.Map("de_stmarc", "https://static.wikia.nocookie.net/cswikia/images/8/83/Stmarc_tspawn.png/revision/latest/scale-to-width-down/1000?cb=20210912141050"),
            new Resources.Map("de_sugarcane", "https://static.wikia.nocookie.net/cswikia/images/c/c7/Csgo-de-sugarcane.png/revision/latest/scale-to-width-down/1000?cb=20140820125612"),
            new Resources.Map("de_train", "https://static.wikia.nocookie.net/cswikia/images/4/4a/De_train_thumbnail.png/revision/latest/scale-to-width-down/1000?cb=20181004200630"),
            new Resources.Map("de_vertigo", "https://static.wikia.nocookie.net/cswikia/images/a/a5/Vertigo-b-site-overview.png/revision/latest/scale-to-width-down/1000?cb=20210901105128"),
            new Resources.Map("dz_blacksite", "https://static.wikia.nocookie.net/cswikia/images/c/c1/Dz_blacksite.png/revision/latest/scale-to-width-down/1000?cb=20201203223002"),
            new Resources.Map("dz_frostbite", "https://static.wikia.nocookie.net/cswikia/images/c/c6/Dz_frostbite.png/revision/latest/scale-to-width-down/1000?cb=20211025085227"),
            new Resources.Map("dz_sirocco", "https://static.wikia.nocookie.net/cswikia/images/7/7f/Sirocco-center.png/revision/latest/scale-to-width-down/1000?cb=20211020085720"),
        ],
        ["H2M"] =
        [ 
            new Resources.Map("mp_convoy", "https://static.wikia.nocookie.net/callofduty/images/3/3c/Bare_Load_Screen_Ambush_CoD4.jpg/revision/latest?cb=20100723075603"),
            new Resources.Map("mp_backlot", "https://static.wikia.nocookie.net/callofduty/images/0/0f/Backlot_loadscreen_CoD4.jpg/revision/latest?cb=20100723075613"),
            new Resources.Map("mp_bloc", "https://static.wikia.nocookie.net/callofduty/images/9/9d/Bare_Load_Screen_Bloc_CoD4.jpg/revision/latest?cb=20100723075638"),
            new Resources.Map("mp_bog", "https://static.wikia.nocookie.net/callofduty/images/2/29/Bog_Map_Image_CoD4.jpg/revision/latest?cb=20100723075648"),
            new Resources.Map("mp_countdown", "https://static.wikia.nocookie.net/callofduty/images/e/e9/Bare_Load_Screen_Countdown_CoD4.jpg/revision/latest?cb=20100723075829"),
            new Resources.Map("mp_crash", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Crash-CoD4.jpg"),
            new Resources.Map("mp_crossfire", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-crossfire.jpg"),
            new Resources.Map("mp_citystreets", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-district.jpg"),
            new Resources.Map("mp_farm", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Downpour-CoD4.jpg"),
            new Resources.Map("mp_overgrown", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Overgrown-CoD4.jpg"),
            new Resources.Map("mp_pipeline", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-pipeline.jpg"),
            new Resources.Map("mp_shipment", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Shipment-Load.jpg"),
            new Resources.Map("mp_showdown", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Showdown-MWR.jpg"),
            new Resources.Map("mp_strike", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Cod4-map-strike.jpg"),
            new Resources.Map("mp_vacant", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640360-Cod4-map-vacant.jpg"),
            new Resources.Map("mp_cargoship", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Cod4-map-wetwork.jpg"),
            new Resources.Map("mp_crash_snow", "https://static.wikia.nocookie.net/callofduty/images/f/f7/Bare_Load_Screen_Winter_Crash_CoD4.jpg/revision/latest?cb=20100723080720"),
            new Resources.Map("mp_broadcast", "https://static.wikia.nocookie.net/callofduty/images/e/ec/Broadcast_loading_screen_CoD4.jpg/revision/latest?cb=20100723080927"),
            new Resources.Map("mp_creek", "https://static.wikia.nocookie.net/callofduty/images/e/e1/CreekCOD4.jpg/revision/latest?cb=20100723075941"),
            new Resources.Map("mp_carentan", "https://static.wikia.nocookie.net/callofduty/images/0/0c/ChinatownCOD4.jpg/revision/latest?cb=20110727174233"),
            new Resources.Map("mp_killhouse", "https://static.wikia.nocookie.net/callofduty/images/4/48/Cod4-killhouse.jpg/revision/latest?cb=20100723081127"),
            new Resources.Map("mp_farm_spring", "https://www.gamegrin.com/assets/Uploads/_resampled/resizedimage640400-Bare-Load-Screen-Downpour-CoD4.jpg"),
            new Resources.Map("mp_bog_summer", "https://static.wikia.nocookie.net/callofduty/images/2/29/Bog_Map_Image_CoD4.jpg/revision/latest?cb=20100723075648"),
            new Resources.Map("airport", "https://static.wikia.nocookie.net/callofduty/images/1/14/Bare_Load_Screen_Terminal_MW2.jpg/revision/latest?cb=20100720174519"),
            new Resources.Map("boneyard", "https://static.wikia.nocookie.net/callofduty/images/e/ef/Scrapyard.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("mp_boneyard", "https://static.wikia.nocookie.net/callofduty/images/e/ef/Scrapyard.jpg/revision/latest?cb=20100720174413"),
            new Resources.Map("oilrig", "https://static.wikia.nocookie.net/callofduty/images/3/30/Mg_oilrig.jpg/revision/latest480?cb=20120716172859"),
            new Resources.Map("estate", "https://static.wikia.nocookie.net/callofduty/images/9/91/Estate.jpg/revision/latest?cb=20100720174409"),
            new Resources.Map("mp_afghan", "https://static.wikia.nocookie.net/callofduty/images/8/83/Afghan_loading_screen_MW2.png/revision/latest?cb=20130310131229"),
            new Resources.Map("mp_complex", "https://static.wikia.nocookie.net/callofduty/images/0/0e/MW2_Bailout.jpg/revision/latest?cb=20100613115812"),
            new Resources.Map("mp_derail", "https://static.wikia.nocookie.net/callofduty/images/2/20/Derail.jpg/revision/latest?cb=20100720174408"),
            new Resources.Map("mp_estate", "https://static.wikia.nocookie.net/callofduty/images/9/91/Estate.jpg/revision/latest?cb=20100720174409"),       
            new Resources.Map("mp_favela", "https://static.wikia.nocookie.net/callofduty/images/2/29/Favela_Map_MW2.jpg/revision/latest?cb=20100720174410"),                   
            new Resources.Map("mp_fuel2", "https://static.wikia.nocookie.net/callofduty/images/d/de/Fuel_loadscreen.jpg/revision/latest?cb=20100712195521"),
            new Resources.Map("mp_highrise", "https://static.wikia.nocookie.net/callofduty/images/4/49/Highrise-promo.jpg/revision/latest?cb=20100720174411"),
            new Resources.Map("mp_invasion", "https://static.wikia.nocookie.net/callofduty/images/9/95/Invasion_MW2.jpg/revision/latest?cb=20100720174410"),
            new Resources.Map("mp_checkpoint", "https://static.wikia.nocookie.net/callofduty/images/9/9f/Karachi-prev.jpg/revision/latest?cb=20100720174412"),
            new Resources.Map("mp_quarry", "https://static.wikia.nocookie.net/callofduty/images/8/8a/Loadscreen_mp_quarry.jpg/revision/latest?cb=20091207173135"),
            new Resources.Map("mp_rundown", "https://static.wikia.nocookie.net/callofduty/images/3/3a/Rundown-prev.jpg/revision/latest?cb=20100720174412"),
            new Resources.Map("mp_rust", "https://static.wikia.nocookie.net/callofduty/images/3/33/Rust.jpg/revision/latest?cb=20100720174413"),        
            new Resources.Map("mp_compact", "https://static.wikia.nocookie.net/callofduty/images/d/d7/MW2_Salvage.jpg/revision/latest?cb=20100613115824"),        
            new Resources.Map("mp_nightshift", "https://static.wikia.nocookie.net/callofduty/images/d/d2/Skidrow.jpg/revision/latest?cb=20100720174516"), 
            new Resources.Map("mp_storm", "https://static.wikia.nocookie.net/callofduty/images/6/60/MW2_Storm.jpg/revision/latest?cb=20100613115722"),
            new Resources.Map("mp_subbase", "https://static.wikia.nocookie.net/callofduty/images/1/1e/Sub_Base.jpg/revision/latest?cb=20100720174517"),
            new Resources.Map("mp_terminal", "https://static.wikia.nocookie.net/callofduty/images/1/14/Bare_Load_Screen_Terminal_MW2.jpg/revision/latest?cb=20100720174519"),
            new Resources.Map("mp_trailerpark", "https://static.wikia.nocookie.net/callofduty/images/c/cf/Trailer_Park.jpg/revision/latest?cb=20100712195448"),
            new Resources.Map("mp_underpass", "https://static.wikia.nocookie.net/callofduty/images/b/b5/Underpass.jpg/revision/latest?cb=20100720174519"),                   
            new Resources.Map("mp_brecourt", "https://static.wikia.nocookie.net/callofduty/images/c/cc/Wasteland.jpg/revision/latest?cb=20100720174520"),  
            new Resources.Map("mp_crash", "https://static.wikia.nocookie.net/callofduty/images/9/9f/Bare_Load_Screen_Crash_MW2.jpg/revision/latest?cb=20100613115705"),
            new Resources.Map("gulag", "https://static.wikia.nocookie.net/callofduty/images/5/53/Mw2_gulag_previewscreen.png/revision/latest?cb=20210625173610"),    
            new Resources.Map("dc_whitehouse", "https://static.wikia.nocookie.net/callofduty/images/6/60/Whiskey_Hotel_menu_image_MW2.png/revision/latest?cb=20161104114740"), 
            new Resources.Map("mp_abandon", "https://static.wikia.nocookie.net/callofduty/images/c/c3/Carnival_loadscreen.jpg/revision/latest/scale-to-width-down/1000?cb=20100712195429"), 
            new Resources.Map("cliffhanger", "https://static.wikia.nocookie.net/callofduty/images/f/fa/Russian_Troops_Cliffhanger_MW2.jpg/revision/latest/scale-to-width-down/1000?cb=20140209031033"), 
            new Resources.Map("contingency", "https://static.wikia.nocookie.net/callofduty/images/a/a8/Desperate_Times_achievement_image_MW2R.png/revision/latest/scale-to-width-down/1000?cb=20200421152033"), 
            new Resources.Map("dcburning",   "https://static.wikia.nocookie.net/callofduty/images/d/db/Washington_D.C._on_fire_Second_Sun_MW2.png/revision/latest/scale-to-width-down/1000?cb=20130116003709"), 
        ],
        ["IW7"] =
        [
            new Resources.Map("mp_frontier", "https://static.wikia.nocookie.net/callofduty/images/f/f8/Frontier_Overview_IW.png/revision/latest/scale-to-width-down/268?cb=20161129030910"),
            new Resources.Map("mp_afghan", "https://static.wikia.nocookie.net/callofduty/images/6/64/Dominion_IW.png/revision/latest/scale-to-width-down/1000?cb=20170331224057"),
            new Resources.Map("mp_depot", "https://static.wikia.nocookie.net/callofduty/images/8/86/Depot_22_Title_IW.png/revision/latest/scale-to-width-down/1000?cb=20170907223336"),
            new Resources.Map("mp_flip", "https://static.wikia.nocookie.net/callofduty/images/c/cf/Excess_IW.jpg/revision/latest?cb=20170404200800"),
            new Resources.Map("mp_geneva", "https://static.wikia.nocookie.net/callofduty/images/2/28/Renaissance_IW.png/revision/latest/scale-to-width-down/1000?cb=20170131160447"),
            new Resources.Map("mp_renaissance2", "https://static.wikia.nocookie.net/callofduty/images/2/28/Renaissance_IW.png/revision/latest/scale-to-width-down/1000?cb=20170131160447"),
            new Resources.Map("mp_hawkwar", "https://static.wikia.nocookie.net/callofduty/images/4/4e/Heartland_Title_IW.png/revision/latest?cb=20170907223351"),
            new Resources.Map("mp_junk", "https://static.wikia.nocookie.net/callofduty/images/b/b4/Scrap_IW.jpg/revision/latest?cb=20170404200813"),
            new Resources.Map("mp_mansion", "https://static.wikia.nocookie.net/callofduty/images/3/3b/Archive_IW.jpg/revision/latest/scale-to-width-down/1000?cb=20170404200740"),
            new Resources.Map("mp_marsoasis", "https://static.wikia.nocookie.net/callofduty/images/8/81/Turista_IW.jpg/revision/latest?cb=20170404200827"),
            new Resources.Map("mp_turista2", "https://static.wikia.nocookie.net/callofduty/images/8/81/Turista_IW.jpg/revision/latest?cb=20170404200827"),
            new Resources.Map("mp_neon", "https://static.wikia.nocookie.net/callofduty/images/3/39/Neon_IW.png/revision/latest?cb=20170131160929"),
            new Resources.Map("mp_nova", "https://static.wikia.nocookie.net/callofduty/images/4/4b/Bermuda_IW.png/revision/latest?cb=20170628041555"),
            new Resources.Map("mp_overflow", "https://static.wikia.nocookie.net/callofduty/images/9/96/Permafrost_IW.png/revision/latest?cb=20170628041715"),
            new Resources.Map("mp_permafrost2", "https://static.wikia.nocookie.net/callofduty/images/9/96/Permafrost_IW.png/revision/latest?cb=20170628041715"),
            new Resources.Map("mp_paris", "https://static.wikia.nocookie.net/callofduty/images/7/7d/Ember_IW.png/revision/latest?cb=20170628041620"),
            new Resources.Map("mp_pixel", "https://static.wikia.nocookie.net/callofduty/images/3/3e/Fore_IW.png/revision/latest?cb=20170628041648"),
            new Resources.Map("mp_prime", "https://static.wikia.nocookie.net/callofduty/images/0/09/Noir_IW.png/revision/latest?cb=20161220221154"),
            new Resources.Map("mp_rally", "https://static.wikia.nocookie.net/callofduty/images/2/27/Carnage_Title_IW.png/revision/latest?cb=20170907223316"),
            new Resources.Map("mp_carnage2", "https://static.wikia.nocookie.net/callofduty/images/2/27/Carnage_Title_IW.png/revision/latest?cb=20170907223316"),
            new Resources.Map("mp_parkour", "https://static.wikia.nocookie.net/callofduty/images/b/b9/Breakout_IW.jpg/revision/latest?cb=20161001191127"),
            new Resources.Map("mp_proto", "https://static.wikia.nocookie.net/callofduty/images/5/5a/Frost_Overview_1_IW.png/revision/latest?cb=20161129030930"),
            new Resources.Map("mp_quarry", "https://static.wikia.nocookie.net/callofduty/images/2/2c/Crusher_Overview_IW.png/revision/latest?cb=20161129030850"),
            new Resources.Map("mp_riot", "https://static.wikia.nocookie.net/callofduty/images/5/51/Retaliation_Overview_IW.png/revision/latest?cb=20161129031205"),
            new Resources.Map("mp_rivet", "https://static.wikia.nocookie.net/callofduty/images/1/10/Skydock_Overview_IW.png/revision/latest?cb=20161129031233"),
            new Resources.Map("mp_skyway", "https://static.wikia.nocookie.net/callofduty/images/2/26/Terminal_Concept_Art_without_Text_IW.png/revision/latest?cb=20230217213511"),
            new Resources.Map("mp_breakneck", "https://static.wikia.nocookie.net/callofduty/images/8/8c/Mayday_Overview_IW.png/revision/latest?cb=20161129031103"),
            new Resources.Map("mp_codphish", "https://static.wikia.nocookie.net/callofduty/images/b/b1/Altitude_Title_IW.png/revision/latest?cb=20170907223258"),
            new Resources.Map("mp_desert", "https://static.wikia.nocookie.net/callofduty/images/8/87/Grounded_IW.png/revision/latest?cb=20240124053941"),
            new Resources.Map("mp_divide", "https://static.wikia.nocookie.net/callofduty/images/d/d4/Scorch_Overview_IW.png/revision/latest?cb=20161129031134"),
            new Resources.Map("mp_dome_iw", "https://static.wikia.nocookie.net/callofduty/images/9/99/Genesis_IW.png/revision/latest?cb=20161107114209"),
            new Resources.Map("mp_fallen", "https://static.wikia.nocookie.net/callofduty/images/3/36/Throwback_IW.png/revision/latest?cb=20170118042431"),
            new Resources.Map("mp_metropolis", "https://static.wikia.nocookie.net/callofduty/images/e/e8/Precient_IW.png/revision/latest?cb=20161108142643"),
            new Resources.Map("cp_zmb", "https://static.wikia.nocookie.net/callofduty/images/d/d3/Zombies_in_Spaceland_Promo.png/revision/latest?cb=20161013220948"),
            new Resources.Map("cp_disco", "https://static.wikia.nocookie.net/callofduty/images/9/9a/Shaolin_Shuffle_Artwork_Large.png/revision/latest?cb=20170907222735"),
            new Resources.Map("cp_final", "https://static.wikia.nocookie.net/callofduty/images/9/99/The_Beast_From_Beyond_Title_Card_IW.png/revision/latest?cb=20170907161409"),
            new Resources.Map("cp_rave", "https://static.wikia.nocookie.net/callofduty/images/1/1c/RaveInTheRedwoods_IW.jpg/revision/latest?cb=20161220181158"),
            new Resources.Map("cp_town", "https://static.wikia.nocookie.net/callofduty/images/a/a2/Attack_of_the_Radioactive_Thing_Title_IW.jpg/revision/latest?cb=20180726034616")
        ],
        ["L4D2"] =
        [
            new Resources.Map("c1m1_hotel", "https://static.wikia.nocookie.net/left4dead/images/6/6e/DeadCenter.jpg"),
            new Resources.Map("c1m2_streets", "https://static.wikia.nocookie.net/left4dead/images/6/6e/DeadCenter.jpg"),
            new Resources.Map("c1m3_mall", "https://static.wikia.nocookie.net/left4dead/images/6/6e/DeadCenter.jpg"),
            new Resources.Map("c1m4_atrium", "https://static.wikia.nocookie.net/left4dead/images/6/6e/DeadCenter.jpg"),
            new Resources.Map("c2m1_highway", "https://static.wikia.nocookie.net/left4dead/images/6/6c/Dark_Carnival02.png"),
            new Resources.Map("c2m2_fairgrounds", "https://static.wikia.nocookie.net/left4dead/images/6/6c/Dark_Carnival02.png"),
            new Resources.Map("c2m3_coaster", "https://static.wikia.nocookie.net/left4dead/images/6/6c/Dark_Carnival02.png"),
            new Resources.Map("c2m4_barns", "https://static.wikia.nocookie.net/left4dead/images/6/6c/Dark_Carnival02.png"),
            new Resources.Map("c2m5_concert", "https://static.wikia.nocookie.net/left4dead/images/6/6c/Dark_Carnival02.png"),
            new Resources.Map("c3m1_plankcountry", "https://static.wikia.nocookie.net/left4dead/images/6/65/TheNewSwampFever.JPG"),
            new Resources.Map("c3m2_swamp", "https://static.wikia.nocookie.net/left4dead/images/6/65/TheNewSwampFever.JPG"),
            new Resources.Map("c3m3_shantytown", "https://static.wikia.nocookie.net/left4dead/images/6/65/TheNewSwampFever.JPG"),
            new Resources.Map("c3m4_plantation", "https://static.wikia.nocookie.net/left4dead/images/6/65/TheNewSwampFever.JPG"),
            // Hard Rain
            new Resources.Map("c4m1_milltown_a", "https://static.wikia.nocookie.net/left4dead/images/c/cd/HardRain.jpg"),
            new Resources.Map("c4m2_sugarmill_a", "https://static.wikia.nocookie.net/left4dead/images/c/cd/HardRain.jpg"),
            new Resources.Map("c4m3_sugarmill_b", "https://static.wikia.nocookie.net/left4dead/images/c/cd/HardRain.jpg"),
            new Resources.Map("c4m4_milltown_b", "https://static.wikia.nocookie.net/left4dead/images/c/cd/HardRain.jpg"),
            new Resources.Map("c4m5_milltown_escape", "https://static.wikia.nocookie.net/left4dead/images/c/cd/HardRain.jpg"),
            // The Parish
            new Resources.Map("c5m1_waterfront", "https://static.wikia.nocookie.net/left4dead/images/e/e8/TheNewParish.jpg"),
            new Resources.Map("c5m2_park", "https://static.wikia.nocookie.net/left4dead/images/e/e8/TheNewParish.jpg"),
            new Resources.Map("c5m3_cemetery", "https://static.wikia.nocookie.net/left4dead/images/e/e8/TheNewParish.jpg"),
            new Resources.Map("c5m4_quarter", "https://static.wikia.nocookie.net/left4dead/images/e/e8/TheNewParish.jpg"),
            new Resources.Map("c5m5_bridge", "https://static.wikia.nocookie.net/left4dead/images/e/e8/TheNewParish.jpg"),
            // The Passing
            new Resources.Map("c6m1_riverbank", "https://static.wikia.nocookie.net/left4dead/images/f/f3/The_Passing_Poster.jpg"),
            new Resources.Map("c6m2_bedlam", "https://static.wikia.nocookie.net/left4dead/images/f/f3/The_Passing_Poster.jpg"),
            new Resources.Map("c6m3_port", "https://static.wikia.nocookie.net/left4dead/images/f/f3/The_Passing_Poster.jpg"),
            // The Sacrifice
            new Resources.Map("c7m1_docks", "https://static.wikia.nocookie.net/left4dead/images/f/ff/It%27s_Your_Funeral.jpg"),
            new Resources.Map("c7m2_barge", "https://static.wikia.nocookie.net/left4dead/images/f/ff/It%27s_Your_Funeral.jpg"),
            new Resources.Map("c7m3_port", "https://static.wikia.nocookie.net/left4dead/images/f/ff/It%27s_Your_Funeral.jpg"),
            // No Mercy (L4D1 campaign ported to L4D2)
            new Resources.Map("c8m1_apartment", "https://static.wikia.nocookie.net/left4dead/images/d/d2/No_Mercy.jpg"),
            new Resources.Map("c8m2_subway", "https://static.wikia.nocookie.net/left4dead/images/d/d2/No_Mercy.jpg"),
            new Resources.Map("c8m3_sewers", "https://static.wikia.nocookie.net/left4dead/images/d/d2/No_Mercy.jpg"),
            new Resources.Map("c8m4_interior", "https://static.wikia.nocookie.net/left4dead/images/d/d2/No_Mercy.jpg"),
            new Resources.Map("c8m5_rooftop", "https://static.wikia.nocookie.net/left4dead/images/d/d2/No_Mercy.jpg"),
            // Crash Course (L4D1)
            new Resources.Map("c9m1_alleys", "https://static.wikia.nocookie.net/left4dead/images/8/89/Crash_Course.jpg"),
            new Resources.Map("c9m2_lots", "https://static.wikia.nocookie.net/left4dead/images/8/89/Crash_Course.jpg"),
            // Death Toll (L4D1)
            new Resources.Map("c10m1_caves", "https://static.wikia.nocookie.net/left4dead/images/9/93/Death_Toll.jpg"),
            new Resources.Map("c10m2_drainage", "https://static.wikia.nocookie.net/left4dead/images/9/93/Death_Toll.jpg"),
            new Resources.Map("c10m3_ranchhouse", "https://static.wikia.nocookie.net/left4dead/images/9/93/Death_Toll.jpg"),
            new Resources.Map("c10m4_mainstreet", "https://static.wikia.nocookie.net/left4dead/images/9/93/Death_Toll.jpg"),
            new Resources.Map("c10m5_houseboat", "https://static.wikia.nocookie.net/left4dead/images/9/93/Death_Toll.jpg"),
            // Dead Air (L4D1)
            new Resources.Map("c11m1_greenhouse", "https://static.wikia.nocookie.net/left4dead/images/8/8c/Dead_Air.jpg"),
            new Resources.Map("c11m2_offices", "https://static.wikia.nocookie.net/left4dead/images/8/8c/Dead_Air.jpg"),
            new Resources.Map("c11m3_garage", "https://static.wikia.nocookie.net/left4dead/images/8/8c/Dead_Air.jpg"),
            new Resources.Map("c11m4_terminal", "https://static.wikia.nocookie.net/left4dead/images/8/8c/Dead_Air.jpg"),
            new Resources.Map("c11m5_runway", "https://static.wikia.nocookie.net/left4dead/images/8/8c/Dead_Air.jpg"),
            // Blood Harvest (L4D1)
            new Resources.Map("c12m1_hilltop", "https://static.wikia.nocookie.net/left4dead/images/0/03/Blood_Harvest.jpg"),
            new Resources.Map("c12m2_traintunnel", "https://static.wikia.nocookie.net/left4dead/images/0/03/Blood_Harvest.jpg"),
            new Resources.Map("c12m3_bridge", "https://static.wikia.nocookie.net/left4dead/images/0/03/Blood_Harvest.jpg"),
            new Resources.Map("c12m4_barn", "https://static.wikia.nocookie.net/left4dead/images/0/03/Blood_Harvest.jpg"),
            new Resources.Map("c12m5_cornfield", "https://static.wikia.nocookie.net/left4dead/images/0/03/Blood_Harvest.jpg"),
            // Cold Stream (Community campaign)
            new Resources.Map("c13m1_alpinecreek", "https://static.wikia.nocookie.net/left4dead/images/2/2c/COLDSTEAMPOSTER.png"),
            new Resources.Map("c13m2_southpinestream", "https://static.wikia.nocookie.net/left4dead/images/2/2c/COLDSTEAMPOSTER.png"),
            new Resources.Map("c13m3_memorialbridge", "https://static.wikia.nocookie.net/left4dead/images/2/2c/COLDSTEAMPOSTER.png"),
            new Resources.Map("c13m4_cutthroatcreek", "https://static.wikia.nocookie.net/left4dead/images/2/2c/COLDSTEAMPOSTER.png"),
            // The Last Stand (Community update)
            new Resources.Map("c14m1_junkyard", "https://static.wikia.nocookie.net/left4dead/images/9/9e/The_Last_Stand.jpg"),
            new Resources.Map("c14m2_lighthouse", "https://static.wikia.nocookie.net/left4dead/images/9/9e/The_Last_Stand.jpg")
        ]
        // @formatter:on
    };
}
